### ISSUE TITLE
RPC error counters

### ISSUE THREAD

**Issue by godmodegalactus** [blockworks-foundation/lite-rpc#131]
Add error counters for RPC, and pubsub each time a request fails to detect that rpc must be down in prometheus.

**Comment by riordanp** [comment]
To clarify, for stateful connections like postgres and pubsub we should publish a 'Gauge' metric with a value of 1 when connected and 0 when not

**Comment by aniketfuryrocks** [comment]
We can add that to when a service fails.
Not sure how can we can do it for each request fail without a lot of boilerplate code

**Comment by godmodegalactus** [comment]
@aniketfuryrocks any updates on this issue?

**Comment by godmodegalactus** [comment]
Dev has been completed by https://github.com/blockworks-foundation/lite-rpc/pull/150
