### ISSUE TITLE
Block subscriptions via yellowstone-geyser + mango-feeds

### ISSUE THREAD

**Issue by grooviegermanikus** [blockworks-foundation/lite-rpc#139]
lite-rpc relies heavily on WebSocket subscription to Full-RPC nodes.

### Problem:

WebSocket-Interfacing come with these downsides:

- heavy resource usage on Full-RPC node both maintaining the subscribers and fanout the requested data
- WebSocket-Protocol is complex which makes clients brittle

### Proposed solution:

Use yellowstone-geyser-plugin to exfiltrate block data using gRPC protocol.

Replace websocket *blockSubscribe* in lite-rpc with yellowstone-gRPC-Subscriptions.

Replace sync RPC-Calls with yellowstone-gRPC-Subscriptions:

- getLatestBlockhash (SubscribeUpdateBlock)
- getBlockTime (SubscribeUpdateBlock)
- getSlot (SubscribeUpdateBlock)

Integrate existing *mango-feeds-connector* library in lite-rpc to manage the connection

### Milestones:

1. Integrate mango-feeds-connector and subscribe using grpc; compare with WebSocket-based update stream.
2. Replace current WebSocket-Subscription with websocket_source from mango-feeds-connector library.
3. Add cli option to switch between WebSocket and gRPC.

**Comment by godmodegalactus** [comment]
Implemented GRPC plugin using https://github.com/blockworks-foundation/lite-rpc/tree/gmg/refactor_gyser_rpc
