### ISSUE TITLE
Linkable Rust library with lite-rpc functionality to send transactions

### ISSUE THREAD

**Issue by grooviegermanikus** [blockworks-foundation/lite-rpc#143]
### Problem:

json rpc is a good interface to integrate arbitrary languages, for rust based users a linkable library would be preferred

### Proposed solution:
Implement a Rust library that covers all (lite-rpc)functionality required to send transactions.
Library should use _mango-feeds-connector_ and the to-be-implemented quic-forward-proxy (https://github.com/blockworks-foundation/lite-rpc/issues/142).

low priority: Retrieve logs related to mango account and allow custom tracing of end-to-end operation

**Comment by grooviegermanikus** [comment]
used ATM for Mango Simulation

**Comment by godmodegalactus** [comment]
The dev has been completed.
