### ISSUE TITLE
lite rpc does not start

### ISSUE THREAD

**Issue by leonardo3dp** [blockworks-foundation/lite-rpc#259]
it has 2 configuration files, one .env and another config.json, which is used to start
cargo run --release

I edited the 2 files, lite-rpc compiles and starts but not even a port is open for communication

**Comment by leonardo3dp** [comment]
the documentation is out of date or doesn't work at all

solana-lite-rpc-quic-forward-proxy --proxy-listen-addr 127.0.0.1:11111

Error: Cannot find the identity file provided

Caused by:
    No such file or directory (os error 2)

shouldn't it start without --identity-keypair ?

**Comment by leonardo3dp** [comment]
RUST_LOG=debug cargo run --bin lite-rpc
even the .env with USE_GRPC false it tries to connect

WARN geyser_grpc_connector::grpc_subscription_autoreconnect: ! subscribe failed on grpc_addr http://127.0.0.0:10000 - retrying: TonicError(tonic::transport::Error(Transport, hype                                                                                                              r::Error(Connect, ConnectError("tcp connect error", Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }))))
2024-01-13T18:24:54.038099Z  WARN geyser_grpc_connector::grpc_subscription_autoreconnect: ! subscribe failed on grpc_addr http://127.0.0.0:10000 - retrying: TonicError(tonic::transport::Error(Transport, hype                                                                                                              r::Error(Connect, ConnectError("tcp connect error", Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }))))

**Comment by aniketfuryrocks** [comment]
Can u share your .env and config ?

**Comment by leonardo3dp** [comment]
I could test it on the machine that runs full RPC

## LiteRpc 
LITE_RPC_HTTP_ADDR=http://0.0.0.0:8890
LITE_RPC_WS_ADDR=[::]:8891

## RPC
RPC_ADDR=http://127.0.0.1:8899
WS_ADDR=ws://127.0.0.1:8900
# IDENTITY=your_identity_keypair_here

## Prometheus
# PROMETHEUS_ADDR=your_prometheus_address_here

## Fanout size and retries configuration
FANOUT_SIZE=32
MAX_RETRIES=40
RETRY_TIMEOUT=3

## Quic Proxy
# QUIC_PROXY_ADDR=your_quic_proxy_address_here

## gRPC Configuration
#USE_GRPC=false
GRPC_ADDR=http://127.0.0.0:10000
# GRPC_X_TOKEN=your_grpc_token_here

## Postgres Configuration
# PG_ENABLED=true
# PG_CONFIG=your_postgres_config_here
# CA_PEM_B64=your_base64_encoded_ca_pem_here
# CLIENT_PKS_B64=your_base64_encoded_client_pks_here
# CLIENT_PKS_PASS=your_client_pks_password_here

## Gso
# DISABLE_GSO=your_disable_gso_setting_here

in the meantime I discovered that I should comment out the USE_GRPC=false line instead of defining falce

something wrong in the code makes it bug if you leave it set to false

**Comment by DevSolana** [comment]
??
