### ISSUE TITLE
no blocks via geyser / yellowstone-rpc

### ISSUE THREAD

**Issue by grooviegermanikus** [blockworks-foundation/lite-rpc#307]
### Problem
LiteRPC fails to receive any blocks from geyser. Other subscriptions might work.

> ERROR solana_lite_rpc_cluster_endpoints::grpc_multiplex: block or block meta stream stopped restaring blocks

**Comment by grooviegermanikus** [comment]
Double-check yellowstone plugin config value **blocks -> account_include_any** must be **true**
```json
            "blocks": {
                "max": 1,
                "account_include_max": 10,
                "account_include_any": true,
                "account_include_reject": ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"],
                "include_transactions": true,
                "include_accounts" : false,
                "include_entries" : false
            }
```

**Comment by grooviegermanikus** [comment]
relates to [PR](https://github.com/rpcpool/yellowstone-grpc/pull/167)

**Comment by grooviegermanikus** [comment]
use this log levels for debugging:

> RUST_LOG=info,solana_lite_rpc_cluster_endpoints=trace,geyser_grpc_connector=debug,lite_rpc=debug

**Comment by pelaricoaus** [comment]
do you need to additionally install the yellowstone plugin? right now experiencing this error, however just using the lite-rpc deps which are yellowstone-grpc-proto and yellowstone-grpc-client, neither of these have the config file? so needing to know whether to additionally manually install the yellowstone full repo into the same directory, or whether we need to make a tweak inside the existing deps that come with the current lite-rpc installation?
