### ISSUE TITLE
Fly Cloud Deployed app is not reachable. 

### ISSUE THREAD

**Issue by hsripathi** [blockworks-foundation/lite-rpc#391]
Hi,

lite RPC deployed in fly is not reachable, It is failing the connection to the app ip. Could you help me to figure out what could be the reason for this ? Is this right lite RPC url to connect ? 'https://fly app IP:8890' ?

`(async () => {
    const connection = new Connection('https://<fly app IP>:8890', 'confirmed');
    const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash();
})();`

Fly Cloud app logs ---
![image](https://github.com/blockworks-foundation/lite-rpc/assets/11950729/ea84cd62-a8a2-457b-b8e3-1ab97a274707)

**Comment by stevenkader** [comment]
Hi, did you ever get it working? I am also having trouble.  Thx.
