### ISSUE TITLE
Invalid params error during transaction confirmation

### ISSUE THREAD

**Issue by vexelgray** [blockworks-foundation/lite-rpc#402]
Hey!

I am using Lite-RPC and everything seems to be working correctly, however, when I try to confirm the transaction, I see this in the logs and the transaction never confirms:

```
2024-06-25T18:08:32.467343Z DEBUG lite_rpc::rpc_pubsub: Error parsing optional "signature" as "Signature": ErrorObject { code: InvalidParams, message: "Invalid params", data: Some(RawValue("invalid type: string \"5RfJ7N9KmMjCg6VYNCFH2zb2X3pNfuDWgimrCLKAAiVzfzN4mETJt8cEibbLxXCttAcURqjP7EGwYiV6LXbp2jWv\", expected struct GenericArray at line 1 column 90")) }
2024-06-25T18:08:32.467399Z DEBUG lite_rpc::rpc_pubsub: Error parsing optional "signature" as "Signature": ErrorObject { code: InvalidParams, message: "Invalid params", data: Some(RawValue("invalid type: string \"5RfJ7N9KmMjCg6VYNCFH2zb2X3pNfuDWgimrCLKAAiVzfzN4mETJt8cEibbLxXCttAcURqjP7EGwYiV6LXbp2jWv\", expected struct GenericArray at line 1 column 90")) }
2024-06-25T18:08:32.467445Z DEBUG lite_rpc::rpc_pubsub: Error parsing optional "signature" as "Signature": ErrorObject { code: InvalidParams, message: "Invalid params", data: Some(RawValue("invalid type: string \"5RfJ7N9KmMjCg6VYNCFH2zb2X3pNfuDWgimrCLKAAiVzfzN4mETJt8cEibbLxXCttAcURqjP7EGwYiV6LXbp2jWv\", expected struct GenericArray at line 1 column 90")) }
```

I am using the following code in my Typescript client:

```
const signature = await this.connection.sendTransaction(transaction)

logger.info(`${new Date().toISOString()} Subscribing to transaction confirmation`);
logger.info(`Signature is ${signature}`);

const confirmedTransaction = await this.connection.confirmTransaction(
    {
        blockhash,
        lastValidBlockHeight,
        signature
    },
    this.connection.commitment
);

if (!confirmedTransaction.value.err){
    return true;
} else {
    return false;
}
```

Could you please help me with this issue?

Regards

**Comment by jcatal** [comment]
Hello,
Try ".... sendTransaction(transaction. Serialize() )" on first line of your ts object.

**Comment by vexelgray** [comment]
Hey @jcatal

The transaction sends correctly and lands, so I believe the way it is constructed is not the issue. The problem occurs when using the confirmation method, as it seems to expect a GenericArray, which is causing the error.

The transaction is a versionedTransaction, which I construct in the following way:

```
const messageV0 = new TransactionMessage({
  instructions: [
    myInstructions,
    ...innerTransaction.instructions,
  ],
  payerKey: wallet.publicKey,
  recentBlockhash: latestBlockHash.blockhash
}).compileToV0Message();

const transaction = new VersionedTransaction(messageV0);
transaction.sign([wallet]);
```

I also tried converting the versionedTransaction to a transaction in the following way, which also works and lands:

```
const message = TransactionMessage.decompile(transaction.message);
let tx = new Transaction();
message.instructions.map((ix) => {
  tx = tx.add(ix);
});
tx.feePayer = message.payerKey;
tx.recentBlockhash = message.recentBlockhash;
let signer: Signer = wallet!

const tx_sig = await sendAndConfirmTransaction(this.connection, tx, [signer]);
```

But the same issue occurs, the transaction lands, but the following error appears:

`Error parsing optional "signature" as "Signature": ErrorObject { code: InvalidParams, message: "Invalid params", data: Some(RawValue("invalid type: string \"5RfJ7N9KmMjCg6VYNCFH2zb2X3pNfuDWgimrCLKAAiVzfzN4mETJt8cEibbLxXCttAcURqjP7EGwYiV6LXbp2jWv\", expected struct GenericArray at line 1 column 90")) }`

**Comment by jcatal** [comment]
You can probably infos about the error, in the source code of lite-rpc : /lite-rpc/src/rpc_pubsub.rs, at line 48

**Comment by vexelgray** [comment]
It seems that doesn't solve the problem, as it can't be imported in the way you mentioned.

Whether I try to import solana_sdk::signature::Signature::from or solana_sdk::signature::Signature::try_from, the compiler shows an error:

```
error[E0432]: unresolved import `solana_sdk::signature::Signature`
 --> lite-rpc/src/rpc_pubsub.rs:8:28
  |
8 | use solana_sdk::signature::Signature::try_from;
  |                            ^^^^^^^^^ `Signature` is a struct, not a module
```

It seems that doesn't solve the problem either...

**Comment by jcatal** [comment]
Maybe :

solana_sdk::signature::from or solana_sdk::signature::try_from,

The problem is surely in this area, as you can see in the source code of solana_sdk_signature.

**Comment by jcatal** [comment]
Hello,
Maybe you may modify the code, instead of modifying the "use solana_sdk::signature..."
For instance if the code contains "signature", or "Signature", then you may modify it following the source code of https://docs.rs/solana-sdk/latest/src/solana_sdk/signature.rs.html#93
--> from(signature: Signature) for example
--> l'm trying to figure out what to do, I have the same problem 
 
I have the same problem than your, it seems to be a problem of arrays too, it says `type|type 'expected instead of [this that].

**Comment by vexelgray** [comment]
It seems new update solve the problem, but only working with Transaction not versionedTransaction

**Comment by godmodegalactus** [comment]
> It seems new update solve the problem, but only working with Transaction not versionedTransaction

How do you send versioned trasnsaction ?

**Comment by godmodegalactus** [comment]
This tests work for me : 

```
test('send and confirm versioned transaction', async () => {
    const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash();
    const message = createVersionedMessage(blockhash, payer.publicKey);
    let versionedTransaction = new VersionedTransaction( message, [payer.secretKey])
    versionedTransaction.sign([payer])
    const signature = await connection.sendRawTransaction(versionedTransaction.serialize(), {});
    console.log(`https://explorer.solana.com/tx/${signature}`);
    await connection.confirmTransaction({
        blockhash,
        lastValidBlockHeight,
        signature,
        abortSignal: undefined
    });
});
```

**Comment by jcatal** [comment]
Thank you godemodegalactus, for your replies and good work, you are very capable
